# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# microk8s for centos7
#
require 'yaml'
settings = YAML.load_file('config.yml')

#join_token = SecureRandom.alphanumeric(32)

Vagrant.configure("2") do |config|
  # disable 127.0.1.1 hostname entry in /etc/hosts because this box is template
  config.vm.allow_hosts_modification = false
  config.ssh.forward_agent = true

  config.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)
  config.vm.synced_folder('.', '/Vagrantfiles', type: 'rsync', disabled: true)

  settings['nodes'].each do |node|
    config.vm.define node['hostname'] do |s|
      s.vm.box = settings['vm']['baseos']
      s.vm.hostname = node['hostname']
      # s.vm.network "private_network", ip: node['ip']

      s.vm.provider :vmware_esxi do |esxi|
        # 構築先のESXiの情報
        esxi.esxi_hostname = settings['esxi']['hostname']
        esxi.esxi_username = settings['esxi']['username']
        esxi.esxi_password = ENV['ESXI_PASSWD']||settings['esxi']['password']
        esxi.esxi_hostport = settings['esxi']['hostport']
        esxi.esxi_virtual_network = settings['esxi']['virtualnetworks']
        esxi.esxi_disk_store = settings['vm']['diskstore']

        # 構築するVMの設定
        esxi.guest_name = node['hostname']
        esxi.clone_from_vm = settings['vm']['cloneos']
#       esxi.guest_guestos = settings['os_type'] 
        esxi.guest_username = settings['guest_user']
        esxi.guest_memsize = node['memory']
        esxi.guest_numvcpus = node['cpus']
        esxi.guest_disk_type = node['disk_type']
        esxi.guest_boot_disk_size = node['disk_size']
        esxi.local_allow_overwrite = 'True'
      end
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.groups = {
      "microk8s_nodes" => settings['nodes'].select{|n| n['type']=="microk8s_node"}.map{|n| n['hostname']},
    }
  end
end

