---
- name: configure c9 server with nginx reverse proxy
  hosts: c9_servers
  become: true
  user: vagrant
  vars_files:
    - inventories/common/vars/c9servers.yml
    - inventories/dev/vars/c9servers.yml

  tasks:
    - name: read nodejs repository
      get_url: url=https://rpm.nodesource.com/setup_12.x dest=/tmp mode=755
    - name: setup nodejs repository
      command: /tmp/setup_12.x
    - name: install rpm packages
      package:
        name: nodejs,git,nginx
        state: present
    - name: install rpm packages for tmux build
      package:
        name: gcc,glibc-static
        state: present
#   - import_tasks: ./tasks/nginx_htpasswd.yml
    - name: git clone cloud9 sdk
      git:
        repo: https://github.com/c9/core.git
        dest: /opt/c9sdk
    - name: change owner of c9sdk to vagrant
      file: path=/opt/c9sdk owner="vagrant" group="vagrant" recurse="yes"
    - name: check c9/installed for vagrant
      stat:
        path: /home/vagrant/.c9/installed
      register: vagrant_c9_installed
    - name: c9 SSH installer for vagrant
      shell: |
        scripts/install-sdk.sh
      args:
        chdir: /opt/c9sdk
        warn: no
      become: yes
      become_user: vagrant
      when: vagrant_c9_installed.stat.exists == false
    - name: install c9 systemd unit file
      template:
        src: inventories/common/conf/cloud9.service.j2
        dest: /etc/systemd/system/cloud9.service
    - name: run c9
      systemd:
        state: started
        name: cloud9.service
        daemon_reload: yes
        enabled: yes

  pre_tasks:
    - name: install packages for nginxinc.nginx
      package:
        name: patch,pcre2
        state: present

  roles:
    - role: geerlingguy.repo-epel
#   - role: linux-system-roles.selinux
#   - role: linux-system-roles.firewall
    - role: nginxinc.nginx
    - role: nginxinc.nginx_config

