esxi:
  hostname: "192.168.1.31"    # ESXi hostname or IP addr
  username: "root"            # ESXi login user
  password: "prompt:"         # ESXi login password("prompt:" as manual ops)
  hostport: 22                # ESXi ssh port
  diskstore: "datastore1"     # datastore of guest

node:
  hostname: "generic-cloud9"
  cpus: 1
  memory: 2048
  disk_type: "thin"

